import test from 'node:test';
import assert from 'node:assert/strict';
import { openDb, createProductivServer, runScheduler } from '../server/productiv.mjs';

async function setup(){
  const db=openDb(':memory:'); const {server}=createProductivServer({db,authMode:'test',distDir:null});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve)); const port=server.address().port,base=`http://127.0.0.1:${port}`;
  const req=async(path,{method='GET',body,token,headers={}}={})=>{const r=await fetch(base+path,{method,headers:{...(token?{authorization:`Bearer ${token}`}:{ }),'content-type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json().catch(()=>({}));return{status:r.status,data}};
  const close=()=>new Promise(resolve=>server.close(resolve)); return{db,base,req,close};
}
async function register(s,name){const agents=(await s.req('/api/orchestration/agents')).data;const agent=agents.find(a=>a.name===name);assert.ok(agent);const invite=await s.req(`/api/orchestration/agents/${agent.id}/invite`,{method:'POST',body:{ttl_minutes:30}});assert.equal(invite.status,200);const reg=await s.req('/api/agent/register',{method:'POST',body:{invite_token:invite.data.invite_token,metadata:{test:true}}});assert.equal(reg.status,200);return{...agent,token:reg.data.agent_token}}

test('runtime registry never claims an unregistered slot is online',async()=>{const s=await setup();try{const r=await s.req('/api/orchestration/summary');assert.equal(r.status,200);assert.equal(r.data.agents.length,6);assert.ok(r.data.agents.every(a=>a.state==='unconfigured'));assert.ok(r.data.agents.some(a=>a.name==='Vivienne St. James'&&a.metadata.base44_app_id==='6a3b84e04eff3530698965c5'));}finally{await s.close()}});

test('invite registration, heartbeat, deterministic routing and evidence gate work end-to-end',async()=>{const s=await setup();try{const dutchess=await register(s,'Dutchess');let hb=await s.req('/api/agent/heartbeat',{method:'POST',token:dutchess.token,body:{}});assert.equal(hb.status,200);const agents=(await s.req('/api/orchestration/agents')).data;assert.equal(agents.find(a=>a.name==='Dutchess').state,'online');
  const task=await s.req('/api/orchestration/tasks',{method:'POST',body:{title:'Run a verified shell check',required_capabilities:['shell'],priority:90}});assert.equal(task.status,201);assert.equal(task.data.status,'assigned');assert.equal(task.data.assignment.agentId,dutchess.id);
  const inbox=await s.req('/api/agent/inbox',{token:dutchess.token});assert.equal(inbox.data.tasks.length,1);const id=inbox.data.tasks[0].id;assert.equal((await s.req(`/api/agent/tasks/${id}/claim`,{method:'POST',token:dutchess.token,body:{}})).status,200);
  const noEvidence=await s.req(`/api/agent/tasks/${id}/complete`,{method:'POST',token:dutchess.token,body:{summary:'done',evidence:[]}});assert.equal(noEvidence.status,400);
  const complete=await s.req(`/api/agent/tasks/${id}/complete`,{method:'POST',token:dutchess.token,body:{summary:'Verified shell check complete',evidence:['sha256:abc123','log:/evidence/run-1.log']}});assert.equal(complete.status,200);
  const tasks=(await s.req('/api/orchestration/tasks')).data;assert.equal(tasks[0].status,'completed');assert.deepEqual(tasks[0].evidence,['sha256:abc123','log:/evidence/run-1.log']);
}finally{await s.close()}});

test('scheduler requests daily check-in and checkout once, preserves runtime metadata, and enforces browser origins',async()=>{const s=await setup();try{const v=await register(s,'Vivienne St. James');const viv=(await s.req('/api/orchestration/agents')).data.find(a=>a.name==='Vivienne St. James');assert.equal(viv.metadata.base44_app_id,'6a3b84e04eff3530698965c5');const sameOrigin=await s.req('/api/orchestration/summary',{headers:{origin:s.base}});assert.equal(sameOrigin.status,200);const crossOrigin=await s.req('/api/orchestration/summary',{headers:{origin:'https://evil.invalid'}});assert.equal(crossOrigin.status,403);const run1=runScheduler(s.db,new Date('2026-08-12T23:30:00Z'));assert.equal(run1.local_date,'2026-08-12');assert.equal(run1.checkins_requested,1);assert.equal(run1.checkouts_requested,1);const run2=runScheduler(s.db,new Date('2026-08-12T23:31:00Z'));assert.equal(run2.checkins_requested,0);assert.equal(run2.checkouts_requested,0);const inbox=await s.req('/api/agent/inbox',{token:v.token});assert.deepEqual(inbox.data.messages.map(m=>m.type).sort(),['checkin_required','checkout_required']);const summary=await s.req('/api/orchestration/summary');assert.equal(summary.data.reports.length,0);}finally{await s.close()}});

test('2026-07-28 MCP is stateless, header-validated and authenticated',async()=>{const s=await setup();try{const c=await register(s,'ChatGPT Harness');const discover=await s.req('/mcp',{method:'POST',token:c.token,headers:{'MCP-Protocol-Version':'2026-07-28','Mcp-Method':'server/discover'},body:{jsonrpc:'2.0',id:1,method:'server/discover',params:{_meta:{'io.modelcontextprotocol/protocolVersion':'2026-07-28','io.modelcontextprotocol/clientInfo':{name:'test',version:'1'}}}}});assert.equal(discover.status,200);assert.ok(discover.data.result.supportedVersions.includes('2026-07-28'));
  const list=await s.req('/mcp',{method:'POST',token:c.token,headers:{'MCP-Protocol-Version':'2026-07-28','Mcp-Method':'tools/list'},body:{jsonrpc:'2.0',id:2,method:'tools/list',params:{_meta:{'io.modelcontextprotocol/protocolVersion':'2026-07-28'}}}});assert.equal(list.status,200);assert.equal(list.data.result.cacheScope,'private');assert.ok(list.data.result.tools.some(t=>t.name==='productiv_complete_task'));
  const mismatch=await s.req('/mcp',{method:'POST',token:c.token,headers:{'MCP-Protocol-Version':'2026-07-28','Mcp-Method':'tools/call','Mcp-Name':'wrong'},body:{jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'productiv_status',arguments:{},_meta:{'io.modelcontextprotocol/protocolVersion':'2026-07-28'}}}});assert.equal(mismatch.status,400);assert.equal(mismatch.data.error.code,-32020);
}finally{await s.close()}});

test('Autom8-style rules execute real actions only when due and record runs',async()=>{const s=await setup();try{const h=await register(s,'Hermes Managed');const rule=await s.req('/api/orchestration/automations',{method:'POST',body:{name:'Daily coordinator handoff',trigger_type:'daily',trigger_config:{hour:9,minute:0},action_type:'send_message',action_config:{to_agent_id:h.id,body:'Check Productiv for today’s assigned duties and post a check-in.'}}});assert.equal(rule.status,201);const run=runScheduler(s.db,new Date('2026-08-12T13:05:00Z'));assert.equal(run.automations_run,1);const inbox=await s.req('/api/agent/inbox',{token:h.token});assert.ok(inbox.data.messages.some(m=>m.body.includes('today’s assigned duties')));const rules=await s.req('/api/orchestration/automations');assert.equal(rules.data[0].run_count,1);assert.equal(rules.data[0].last_error,null);}finally{await s.close()}});
