import { randomUUID } from 'node:crypto';
import { audit, nowIso, reply } from './core.mjs';

const MODERN='2026-07-28',LEGACY='2025-11-25',SERVER_INFO={name:'productiv-orchestrator',version:'1.0.0'};
export function mcp(db,req,res,agentId,body){const id=body.id??null,method=String(body.method||''),protocol=String(req.headers['mcp-protocol-version']||body.params?._meta?.['io.modelcontextprotocol/protocolVersion']||''),modern=protocol===MODERN,stamp=modern?{_meta:{'io.modelcontextprotocol/serverInfo':SERVER_INFO}}:{};const ok=result=>reply(res,200,{jsonrpc:'2.0',id,result:{...result,...stamp}}),fail=(code,message,status=200)=>reply(res,status,{jsonrpc:'2.0',id,error:{code,message}});
  if(modern){if(String(req.headers['mcp-method']||'')!==method)return fail(-32020,'Mcp-Method header mismatch',400);if(method==='tools/call'&&String(req.headers['mcp-name']||'')!==String(body.params?.name||''))return fail(-32020,'Mcp-Name header mismatch',400)}
  if(method==='server/discover')return ok({resultType:'complete',supportedVersions:[MODERN,LEGACY],capabilities:{tools:{}},instructions:'Authenticated Productiv task intake, runtime messaging, status, and evidence-backed completion.'});
  if(!modern&&method==='initialize')return ok({protocolVersion:LEGACY,capabilities:{tools:{}},serverInfo:SERVER_INFO});if(!modern&&method==='notifications/initialized'){res.writeHead(202);return res.end()}if(method==='ping')return ok({resultType:'complete'});
  const tools=[{name:'productiv_status',description:'Read verified orchestration status',inputSchema:{type:'object',properties:{},additionalProperties:false}},{name:'productiv_list_tasks',description:'List tasks assigned to this runtime',inputSchema:{type:'object',properties:{status:{type:'string'}},additionalProperties:false}},{name:'productiv_post_message',description:'Post a message to another Productiv runtime',inputSchema:{type:'object',required:['to_agent_id','body'],properties:{to_agent_id:{type:'string'},body:{type:'string'},task_id:{type:'string'}},additionalProperties:false}},{name:'productiv_complete_task',description:'Complete an assigned task with verifiable evidence',inputSchema:{type:'object',required:['task_id','summary','evidence'],properties:{task_id:{type:'string'},summary:{type:'string'},evidence:{type:'array',minItems:1,items:{type:'string'}}},additionalProperties:false}}];
  if(method==='tools/list')return ok({resultType:'complete',ttlMs:60000,cacheScope:'private',tools});if(method!=='tools/call')return fail(-32601,'Method not found',modern?404:200);
  const name=body.params?.name,args=body.params?.arguments||{},toolOk=data=>ok({resultType:'complete',content:[{type:'text',text:JSON.stringify(data)}]});
  if(name==='productiv_status')return toolOk({agents:db.prepare(`SELECT id,name,kind,registered,last_seen_at,last_error FROM runtime_agents ORDER BY name`).all(),tasks:db.prepare(`SELECT status,COUNT(*) count FROM orchestration_tasks GROUP BY status`).all(),server_time:nowIso()});
  if(name==='productiv_list_tasks')return toolOk(db.prepare(`SELECT * FROM orchestration_tasks WHERE assignee_agent_id=? AND (? IS NULL OR status=?) ORDER BY priority DESC,created_at`).all(agentId,args.status||null,args.status||null));
  if(name==='productiv_post_message'){const mid=randomUUID(),corr=randomUUID();db.prepare(`INSERT INTO bus_messages(id,correlation_id,from_agent_id,to_agent_id,task_id,type,body,created_at) VALUES(?,?,?,?,?,'message',?,?)`).run(mid,corr,agentId,args.to_agent_id,args.task_id||null,String(args.body||''),nowIso());audit(db,`agent:${agentId}`,'message.sent','message',mid,{to:args.to_agent_id},corr);return toolOk({id:mid,correlation_id:corr})}
  if(name==='productiv_complete_task'){if(!Array.isArray(args.evidence)||!args.evidence.length)return fail(-32602,'Evidence is required');const r=db.prepare(`UPDATE orchestration_tasks SET status='completed',result_summary=?,evidence_json=?,completed_at=?,updated_at=? WHERE id=? AND assignee_agent_id=? AND status!='completed'`).run(String(args.summary||''),JSON.stringify(args.evidence),nowIso(),nowIso(),args.task_id,agentId);if(!r.changes)return fail(-32004,'Task not found or not assigned to this runtime');audit(db,`agent:${agentId}`,'task.completed','task',args.task_id,{evidence:args.evidence});return toolOk({completed:true,task_id:args.task_id})}
  return fail(-32601,'Unknown tool');
}
