import { createServer } from 'node:http';
import { randomBytes, randomUUID } from 'node:crypto';
import path from 'node:path';
import { adminActor, agentActor, audit, chooseAssignee, hash, jsonBody, nowIso, openDb, parse, publicAgent, reply, tx, verifyConnector } from './core.mjs';
import { mcp } from './mcp.mjs';
import { runScheduler } from './scheduler.mjs';
import { serveStatic } from './static.mjs';

export function createProductivServer({db=openDb(),authMode=process.env.PRODUCTIV_AUTH_MODE||'supabase',distDir=process.env.PRODUCTIV_DIST_DIR||path.resolve('dist')}={}){
  const server=createServer(async(req,res)=>{try{
    const origin=req.headers.origin,allowed=(process.env.PRODUCTIV_ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);if(origin){if(!allowed.includes(origin))return reply(res,403,{error:'origin_not_allowed'});res.setHeader('access-control-allow-origin',origin);res.setHeader('vary','Origin')}if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-methods':'GET,POST,PATCH,OPTIONS','access-control-allow-headers':'Authorization,Content-Type,MCP-Protocol-Version,Mcp-Method,Mcp-Name'});return res.end()}
    const u=new URL(req.url,'http://localhost'),p=u.pathname,method=req.method||'GET';if(p==='/healthz'&&method==='GET')return reply(res,200,{ok:true,service:'productiv-orchestrator',time:nowIso()});
    if(p==='/api/agent/register'&&method==='POST'){const b=await jsonBody(req),token=String(b.invite_token||''),invite=db.prepare(`SELECT * FROM agent_invites WHERE token_hash=? AND used_at IS NULL AND expires_at>?`).get(hash(token),nowIso());if(!invite)throw Object.assign(new Error('invalid_or_expired_invite'),{status:401});const agentToken=randomBytes(32).toString('base64url'),now=nowIso();tx(db,()=>{db.prepare(`INSERT INTO agent_tokens(id,agent_id,token_hash,created_at) VALUES(?,?,?,?)`).run(randomUUID(),invite.agent_id,hash(agentToken),now);db.prepare(`UPDATE agent_invites SET used_at=? WHERE id=?`).run(now,invite.id);db.prepare(`UPDATE runtime_agents SET registered=1,metadata_json=?,updated_at=? WHERE id=?`).run(JSON.stringify(b.metadata||{}),now,invite.agent_id);audit(db,`agent:${invite.agent_id}`,'agent.registered','agent',invite.agent_id)});return reply(res,200,{agent_id:invite.agent_id,agent_token:agentToken,issued_once:true})}
    if(p==='/mcp'&&method==='POST'){const origin=req.headers.origin,mcpAllowed=(process.env.PRODUCTIV_MCP_ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);if(origin&&mcpAllowed.length&&!mcpAllowed.includes(origin))throw Object.assign(new Error('origin_not_allowed'),{status:403});const {agentId}=agentActor(db,req),b=await jsonBody(req);return mcp(db,req,res,agentId,b)}
    if(p.startsWith('/api/agent/')){const {actor,agentId}=agentActor(db,req),b=method==='POST'?await jsonBody(req):{};
      if(p==='/api/agent/heartbeat'&&method==='POST'){const now=nowIso();db.prepare(`UPDATE runtime_agents SET last_seen_at=?,last_error=NULL,updated_at=? WHERE id=?`).run(now,now,agentId);audit(db,actor,'heartbeat','agent',agentId);return reply(res,200,{ok:true,server_time:now})}
      if(p==='/api/agent/inbox'&&method==='GET')return reply(res,200,{tasks:db.prepare(`SELECT * FROM orchestration_tasks WHERE assignee_agent_id=? AND status IN ('assigned','claimed','in_progress') ORDER BY priority DESC,created_at`).all(agentId).map(t=>({...t,required_capabilities:parse(t.required_capabilities_json),evidence:parse(t.evidence_json)})),messages:db.prepare(`SELECT * FROM bus_messages WHERE to_agent_id=? AND read_at IS NULL ORDER BY created_at`).all(agentId)});
      let m=p.match(/^\/api\/agent\/messages\/([^/]+)\/read$/);if(m&&method==='POST'){db.prepare(`UPDATE bus_messages SET read_at=? WHERE id=? AND to_agent_id=?`).run(nowIso(),m[1],agentId);return reply(res,200,{ok:true})}
      m=p.match(/^\/api\/agent\/tasks\/([^/]+)\/(claim|progress|complete)$/);if(m&&method==='POST'){const [_,id,action]=m;if(action==='claim'){const now=nowIso(),r=db.prepare(`UPDATE orchestration_tasks SET status='claimed',claimed_at=?,updated_at=? WHERE id=? AND assignee_agent_id=? AND status='assigned'`).run(now,now,id,agentId);if(!r.changes)throw Object.assign(new Error('task_not_claimable'),{status:409});audit(db,actor,'task.claimed','task',id);return reply(res,200,{ok:true})}if(action==='progress'){const summary=String(b.summary||'').trim();if(!summary)throw Object.assign(new Error('summary_required'),{status:400});const now=nowIso(),r=db.prepare(`UPDATE orchestration_tasks SET status='in_progress',updated_at=? WHERE id=? AND assignee_agent_id=? AND status IN ('assigned','claimed','in_progress')`).run(now,id,agentId);if(!r.changes)throw Object.assign(new Error('task_not_found'),{status:404});const mid=randomUUID(),corr=String(b.correlation_id||randomUUID());db.prepare(`INSERT INTO bus_messages(id,correlation_id,from_agent_id,task_id,type,body,created_at) VALUES(?,?,?,?, 'progress',?,?)`).run(mid,corr,agentId,id,summary,now);audit(db,actor,'task.progress','task',id,{summary},corr);return reply(res,200,{ok:true})}const summary=String(b.summary||'').trim(),evidence=b.evidence;if(!summary||!Array.isArray(evidence)||!evidence.length||evidence.some(x=>typeof x!=='string'||!x.trim()))throw Object.assign(new Error('summary_and_nonempty_evidence_required'),{status:400});const now=nowIso(),r=db.prepare(`UPDATE orchestration_tasks SET status='completed',result_summary=?,evidence_json=?,completed_at=?,updated_at=? WHERE id=? AND assignee_agent_id=? AND status IN ('assigned','claimed','in_progress')`).run(summary,JSON.stringify(evidence),now,now,id,agentId);if(!r.changes)throw Object.assign(new Error('task_not_found'),{status:404});audit(db,actor,'task.completed','task',id,{evidence});return reply(res,200,{ok:true})}
      if(p==='/api/agent/delegate'&&method==='POST'){const parent=String(b.parent_task_id||''),title=String(b.title||'').trim(),owns=db.prepare(`SELECT id,correlation_id,project_id FROM orchestration_tasks WHERE id=? AND assignee_agent_id=?`).get(parent,agentId);if(!owns)throw Object.assign(new Error('parent_task_not_owned'),{status:403});const required=Array.isArray(b.required_capabilities)?b.required_capabilities.map(String):[],route=chooseAssignee(db,required),id=randomUUID(),now=nowIso();db.prepare(`INSERT INTO orchestration_tasks(id,correlation_id,parent_task_id,project_id,title,description,required_capabilities_json,priority,status,assignee_agent_id,routing_reason,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,owns.correlation_id,parent,owns.project_id,title,String(b.description||''),JSON.stringify(required),Number(b.priority||50),route?'assigned':'queued',route?.agentId||null,route?.reason||'no_registered_capability_match',actor,now,now);audit(db,actor,'task.delegated','task',id,{parent,route},owns.correlation_id);return reply(res,201,{id,assignment:route})}
      if(p==='/api/agent/messages'&&method==='POST'){const to=String(b.to_agent_id||''),body=String(b.body||'').trim();if(!to||!body)throw Object.assign(new Error('to_agent_id_and_body_required'),{status:400});if(!db.prepare(`SELECT id FROM runtime_agents WHERE id=? AND enabled=1`).get(to))throw Object.assign(new Error('target_agent_not_found'),{status:404});const id=randomUUID(),corr=String(b.correlation_id||randomUUID());db.prepare(`INSERT INTO bus_messages(id,correlation_id,from_agent_id,to_agent_id,task_id,type,body,created_at) VALUES(?,?,?,?,?,'message',?,?)`).run(id,corr,agentId,to,b.task_id||null,body,nowIso());audit(db,actor,'message.sent','message',id,{to},corr);return reply(res,201,{id,correlation_id:corr})}
      m=p.match(/^\/api\/agent\/reports\/(checkin|checkout)$/);if(m&&method==='POST'){const type=m[1],summary=String(b.summary||'').trim(),evidence=Array.isArray(b.evidence)?b.evidence:[];if(!summary)throw Object.assign(new Error('summary_required'),{status:400});const date=String(b.report_date||new Date().toISOString().slice(0,10));db.prepare(`INSERT INTO daily_reports(id,agent_id,report_type,report_date,summary,evidence_json,created_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(agent_id,report_type,report_date) DO UPDATE SET summary=excluded.summary,evidence_json=excluded.evidence_json,created_at=excluded.created_at`).run(randomUUID(),agentId,type,date,summary,JSON.stringify(evidence),nowIso());audit(db,actor,`report.${type}`,'agent',agentId,{date});return reply(res,200,{ok:true,report_date:date})}
      throw Object.assign(new Error('not_found'),{status:404});
    }
    if(p.startsWith('/api/orchestration/')){const actor=await adminActor(req,authMode),b=['POST','PATCH'].includes(method)?await jsonBody(req):{};
      if(p==='/api/orchestration/summary'&&method==='GET'){const agents=db.prepare(`SELECT * FROM runtime_agents ORDER BY name`).all().map(publicAgent),task_counts=db.prepare(`SELECT status,COUNT(*) count FROM orchestration_tasks GROUP BY status`).all(),reports=db.prepare(`SELECT r.*,a.name agent_name FROM daily_reports r JOIN runtime_agents a ON a.id=r.agent_id ORDER BY r.created_at DESC LIMIT 20`).all(),events=db.prepare(`SELECT * FROM event_log ORDER BY created_at DESC LIMIT 40`).all().map(e=>({...e,detail:parse(e.detail_json,{}),detail_json:undefined}));return reply(res,200,{agents,task_counts,reports,events,server_time:nowIso()})}
      if(p==='/api/orchestration/agents'&&method==='GET')return reply(res,200,db.prepare(`SELECT * FROM runtime_agents ORDER BY name`).all().map(publicAgent));
      if(p==='/api/orchestration/agents'&&method==='POST'){const name=String(b.name||'').trim(),kind=String(b.kind||'').trim();if(!name||!kind)throw Object.assign(new Error('name_and_kind_required'),{status:400});const id=randomUUID(),now=nowIso(),caps=Array.isArray(b.capabilities)?b.capabilities.map(String):[];try{db.prepare(`INSERT INTO runtime_agents(id,name,kind,transport,endpoint,capabilities_json,registered,created_at,updated_at) VALUES(?,?,?,?,?,?,0,?,?)`).run(id,name,kind,String(b.transport||'pull'),b.endpoint||null,JSON.stringify(caps),now,now)}catch{throw Object.assign(new Error('agent_name_already_exists'),{status:409})}audit(db,actor,'agent.slot_created','agent',id,{name,kind});return reply(res,201,{id})}
      let m=p.match(/^\/api\/orchestration\/agents\/([^/]+)\/invite$/);if(m&&method==='POST'){if(!db.prepare(`SELECT id FROM runtime_agents WHERE id=?`).get(m[1]))throw Object.assign(new Error('agent_not_found'),{status:404});const token=randomBytes(24).toString('base64url'),ttl=Math.min(Math.max(Number(b.ttl_minutes||60),5),1440),expires=new Date(Date.now()+ttl*60000).toISOString();db.prepare(`INSERT INTO agent_invites(id,agent_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)`).run(randomUUID(),m[1],hash(token),expires,nowIso());audit(db,actor,'invite.created','agent',m[1],{expires});return reply(res,200,{invite_token:token,expires_at:expires,issued_once:true})}
      m=p.match(/^\/api\/orchestration\/agents\/([^/]+)$/);if(m&&method==='PATCH'){const c=db.prepare(`SELECT * FROM runtime_agents WHERE id=?`).get(m[1]);if(!c)throw Object.assign(new Error('agent_not_found'),{status:404});const caps=Array.isArray(b.capabilities)?b.capabilities.map(String):parse(c.capabilities_json),enabled=b.enabled===undefined?c.enabled:(b.enabled?1:0);db.prepare(`UPDATE runtime_agents SET endpoint=?,transport=?,capabilities_json=?,enabled=?,updated_at=? WHERE id=?`).run(b.endpoint??c.endpoint,b.transport??c.transport,JSON.stringify(caps),enabled,nowIso(),m[1]);audit(db,actor,'agent.updated','agent',m[1],{caps,enabled});return reply(res,200,{ok:true})}
      if(p==='/api/orchestration/tasks'&&method==='GET')return reply(res,200,db.prepare(`SELECT t.*,a.name assignee_name FROM orchestration_tasks t LEFT JOIN runtime_agents a ON a.id=t.assignee_agent_id ORDER BY t.created_at DESC LIMIT 300`).all().map(t=>({...t,required_capabilities:parse(t.required_capabilities_json),evidence:parse(t.evidence_json),required_capabilities_json:undefined,evidence_json:undefined})));
      if(p==='/api/orchestration/tasks'&&method==='POST'){const title=String(b.title||'').trim();if(!title)throw Object.assign(new Error('title_required'),{status:400});const required=Array.isArray(b.required_capabilities)?b.required_capabilities.map(String):[],route=b.assignee_agent_id?{agentId:String(b.assignee_agent_id),reason:'explicit_assignment'}:chooseAssignee(db,required),id=randomUUID(),corr=String(b.correlation_id||randomUUID()),now=nowIso();db.prepare(`INSERT INTO orchestration_tasks(id,correlation_id,project_id,title,description,required_capabilities_json,priority,status,assignee_agent_id,routing_reason,due_at,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,corr,b.project_id||null,title,String(b.description||''),JSON.stringify(required),Number(b.priority||50),route?'assigned':'queued',route?.agentId||null,route?.reason||'no_registered_capability_match',b.due_at||null,actor,now,now);audit(db,actor,'task.created','task',id,{route,required},corr);return reply(res,201,{id,correlation_id:corr,status:route?'assigned':'queued',assignment:route})}
      m=p.match(/^\/api\/orchestration\/tasks\/([^/]+)\/route$/);if(m&&method==='POST'){const t=db.prepare(`SELECT required_capabilities_json FROM orchestration_tasks WHERE id=?`).get(m[1]);if(!t)throw Object.assign(new Error('task_not_found'),{status:404});const route=chooseAssignee(db,parse(t.required_capabilities_json));if(!route)throw Object.assign(new Error('no_registered_capability_match'),{status:409});db.prepare(`UPDATE orchestration_tasks SET assignee_agent_id=?,routing_reason=?,status='assigned',updated_at=? WHERE id=? AND status='queued'`).run(route.agentId,route.reason,nowIso(),m[1]);audit(db,actor,'task.routed','task',m[1],{route});return reply(res,200,route)}
      if(p==='/api/orchestration/connectors'&&method==='GET')return reply(res,200,db.prepare(`SELECT * FROM connectors ORDER BY name`).all().map(c=>({...c,metadata:parse(c.metadata_json,{}),metadata_json:undefined})));
      if(p==='/api/orchestration/connectors'&&method==='POST'){const name=String(b.name||'').trim(),type=String(b.connector_type||'').trim();if(!name||!type)throw Object.assign(new Error('name_and_connector_type_required'),{status:400});const id=randomUUID(),now=nowIso();db.prepare(`INSERT INTO connectors(id,name,connector_type,transport,endpoint,secret_ref,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?)`).run(id,name,type,String(b.transport||'http'),b.endpoint||null,b.secret_ref||null,now,now);audit(db,actor,'connector.created','connector',id,{type});return reply(res,201,{id})}
      m=p.match(/^\/api\/orchestration\/connectors\/([^/]+)\/verify$/);if(m&&method==='POST'){const c=db.prepare(`SELECT * FROM connectors WHERE id=?`).get(m[1]);if(!c)throw Object.assign(new Error('connector_not_found'),{status:404});const v=await verifyConnector(db,c),now=nowIso();db.prepare(`UPDATE connectors SET verification_status=?,last_verified_at=?,last_error=?,updated_at=? WHERE id=?`).run(v.status,v.status==='verified'?now:null,v.error,now,c.id);audit(db,actor,'connector.verified','connector',c.id,v);return reply(res,v.status==='verified'?200:502,{status:v.status,last_verified_at:v.status==='verified'?now:null,error:v.error})}
      if(p==='/api/orchestration/messages'&&method==='GET')return reply(res,200,db.prepare(`SELECT m.*,fa.name from_name,ta.name to_name FROM bus_messages m LEFT JOIN runtime_agents fa ON fa.id=m.from_agent_id LEFT JOIN runtime_agents ta ON ta.id=m.to_agent_id ORDER BY m.created_at DESC LIMIT 300`).all());
      if(p==='/api/orchestration/messages'&&method==='POST'){const to=String(b.to_agent_id||''),body=String(b.body||'').trim();if(!to||!body)throw Object.assign(new Error('to_agent_id_and_body_required'),{status:400});const id=randomUUID(),corr=String(b.correlation_id||randomUUID());db.prepare(`INSERT INTO bus_messages(id,correlation_id,to_agent_id,task_id,type,body,created_at) VALUES(?,?,?,?, 'message',?,?)`).run(id,corr,to,b.task_id||null,body,nowIso());audit(db,actor,'message.sent','message',id,{to},corr);return reply(res,201,{id,correlation_id:corr})}
      if(p==='/api/orchestration/automations'&&method==='GET')return reply(res,200,db.prepare(`SELECT * FROM automation_rules ORDER BY created_at DESC`).all().map(r=>({...r,trigger_config:parse(r.trigger_config_json,{}),action_config:parse(r.action_config_json,{}),trigger_config_json:undefined,action_config_json:undefined})));
      if(p==='/api/orchestration/automations'&&method==='POST'){const name=String(b.name||'').trim(),tt=String(b.trigger_type||''),at=String(b.action_type||'');if(!name||!['interval_minutes','daily'].includes(tt)||!['create_task','send_message'].includes(at))throw Object.assign(new Error('invalid_automation_definition'),{status:400});const id=randomUUID(),now=nowIso(),tc=b.trigger_config||{},ac=b.action_config||{};if(tt==='interval_minutes'&&Number(tc.minutes)<1)throw Object.assign(new Error('interval_must_be_at_least_1_minute'),{status:400});if(tt==='daily'&&(Number(tc.hour)<0||Number(tc.hour)>23||Number(tc.minute)<0||Number(tc.minute)>59))throw Object.assign(new Error('invalid_daily_time'),{status:400});db.prepare(`INSERT INTO automation_rules(id,name,enabled,trigger_type,trigger_config_json,action_type,action_config_json,last_run_at,created_at,updated_at) VALUES(?,?,1,?,?,?,?,?,?,?)`).run(id,name,tt,JSON.stringify(tc),at,JSON.stringify(ac),tt==='interval_minutes'?now:null,now,now);audit(db,actor,'automation.created','automation',id,{trigger_type:tt,action_type:at});return reply(res,201,{id})}
      let am=p.match(/^\/api\/orchestration\/automations\/([^/]+)$/);if(am&&method==='PATCH'){const r=db.prepare(`SELECT * FROM automation_rules WHERE id=?`).get(am[1]);if(!r)throw Object.assign(new Error('automation_not_found'),{status:404});const enabled=b.enabled===undefined?r.enabled:(b.enabled?1:0);db.prepare(`UPDATE automation_rules SET enabled=?,name=?,updated_at=? WHERE id=?`).run(enabled,b.name??r.name,nowIso(),am[1]);audit(db,actor,'automation.updated','automation',am[1],{enabled});return reply(res,200,{ok:true})}
      if(p==='/api/orchestration/events'&&method==='GET')return reply(res,200,db.prepare(`SELECT * FROM event_log ORDER BY created_at DESC LIMIT 500`).all().map(e=>({...e,detail:parse(e.detail_json,{}),detail_json:undefined})));
      if(p==='/api/orchestration/scheduler/run'&&method==='POST'){const result=runScheduler(db);audit(db,actor,'scheduler.manual_run','scheduler','main',result);return reply(res,200,{ok:true,...result})}
      throw Object.assign(new Error('not_found'),{status:404});
    }
    if(await serveStatic(req,res,distDir))return;throw Object.assign(new Error('not_found'),{status:404});
  }catch(e){reply(res,e?.status||500,{error:e instanceof Error?e.message:'internal_error'})}});
  return{server,db};
}
