import { useCallback, useEffect, useState } from 'react';
import { TopBar } from '@/components/Sidebar';
import { orchestratorFetch, type RuntimeAgent } from '@/lib/orchestrator';
import { Activity, Clock3, Loader2, Pause, Play, Plus, RefreshCw, Workflow, XCircle } from 'lucide-react';

type Rule={id:string;name:string;enabled:number;trigger_type:'interval_minutes'|'daily';trigger_config:Record<string,number>;action_type:'create_task'|'send_message';action_config:Record<string,unknown>;last_run_at:string|null;last_error:string|null;run_count:number;created_at:string};
export function AutomationsPage(){
 const [rules,setRules]=useState<Rule[]>([]),[agents,setAgents]=useState<RuntimeAgent[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const [form,setForm]=useState({name:'',trigger_type:'daily',hour:'8',minute:'0',interval:'60',action_type:'create_task',title:'',description:'',capabilities:'',priority:'50',to:'',body:''});
 const load=useCallback(async()=>{try{setError('');const [r,a]=await Promise.all([orchestratorFetch<Rule[]>('/api/orchestration/automations'),orchestratorFetch<RuntimeAgent[]>('/api/orchestration/agents')]);setRules(r);setAgents(a)}catch(e){setError(e instanceof Error?e.message:'Automation engine unavailable')}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 const create=async()=>{if(!form.name.trim())return;setBusy('create');try{const trigger_config=form.trigger_type==='daily'?{hour:Number(form.hour),minute:Number(form.minute)}:{minutes:Number(form.interval)};const action_config=form.action_type==='create_task'?{title:form.title.trim()||form.name.trim(),description:form.description.trim(),required_capabilities:form.capabilities.split(',').map(x=>x.trim()).filter(Boolean),priority:Number(form.priority)||50}:{to_agent_id:form.to,body:form.body.trim()};await orchestratorFetch('/api/orchestration/automations',{method:'POST',body:JSON.stringify({name:form.name.trim(),trigger_type:form.trigger_type,trigger_config,action_type:form.action_type,action_config})});setForm({...form,name:'',title:'',description:'',capabilities:'',body:''});await load()}catch(e){setError(e instanceof Error?e.message:'Create failed')}finally{setBusy('')}};
 const toggle=async(r:Rule)=>{setBusy(r.id);try{await orchestratorFetch(`/api/orchestration/automations/${r.id}`,{method:'PATCH',body:JSON.stringify({enabled:!r.enabled})});await load()}catch(e){setError(e instanceof Error?e.message:'Update failed')}finally{setBusy('')}};
 const run=async()=>{setBusy('run');try{await orchestratorFetch('/api/orchestration/scheduler/run',{method:'POST',body:'{}'});await load()}catch(e){setError(e instanceof Error?e.message:'Run failed')}finally{setBusy('')}};
 return <div className="flex-1 flex flex-col overflow-hidden"><TopBar title="Automations" subtitle="Productiv + Autom8-it: real timer-driven routing without paid automation services" actions={<div className="flex gap-2"><button className="btn-secondary" onClick={load}><RefreshCw className="w-4 h-4"/>Refresh</button><button className="btn-primary" onClick={run} disabled={busy==='run'}>{busy==='run'?<Loader2 className="w-4 h-4 animate-spin"/>:<Play className="w-4 h-4"/>}Run due now</button></div>}/><div className="flex-1 overflow-y-auto mesh-bg p-6"><div className="max-w-6xl mx-auto space-y-5">
 {error&&<div className="card p-4 border-rose-200 bg-rose-50 text-rose-700 text-sm flex gap-2"><XCircle className="w-4 h-4"/>{error}</div>}
 <div className="grid lg:grid-cols-[390px_1fr] gap-5"><div className="card p-5 h-fit"><div className="flex items-center gap-2 mb-4"><Workflow className="w-5 h-5 text-brand-600"/><h3 className="font-bold text-slate-900">New automation</h3></div><div className="space-y-3"><input className="input" placeholder="Automation name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label className="text-xs font-semibold text-slate-500">Trigger</label><select className="input" value={form.trigger_type} onChange={e=>setForm({...form,trigger_type:e.target.value})}><option value="daily">Daily time</option><option value="interval_minutes">Every N minutes</option></select>{form.trigger_type==='daily'?<div className="grid grid-cols-2 gap-2"><input className="input" type="number" min="0" max="23" value={form.hour} onChange={e=>setForm({...form,hour:e.target.value})}/><input className="input" type="number" min="0" max="59" value={form.minute} onChange={e=>setForm({...form,minute:e.target.value})}/></div>:<input className="input" type="number" min="1" value={form.interval} onChange={e=>setForm({...form,interval:e.target.value})}/>}<label className="text-xs font-semibold text-slate-500">Action</label><select className="input" value={form.action_type} onChange={e=>setForm({...form,action_type:e.target.value})}><option value="create_task">Create + route duty</option><option value="send_message">Send runtime message</option></select>{form.action_type==='create_task'?<><input className="input" placeholder="Duty title (defaults to rule name)" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea className="input min-h-20" placeholder="Instructions / acceptance criteria" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input className="input" placeholder="Capabilities, comma-separated" value={form.capabilities} onChange={e=>setForm({...form,capabilities:e.target.value})}/><input className="input" type="number" min="1" max="100" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}/></>:<><select className="input" value={form.to} onChange={e=>setForm({...form,to:e.target.value})}><option value="">Target runtime</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name} — {a.state}</option>)}</select><textarea className="input min-h-24" placeholder="Message" value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></>}<button className="btn-primary w-full" disabled={busy==='create'||!form.name.trim()||(form.action_type==='send_message'&&(!form.to||!form.body.trim()))} onClick={create}>{busy==='create'?<Loader2 className="w-4 h-4 animate-spin"/>:<Plus className="w-4 h-4"/>}Activate automation</button><p className="text-[11px] text-slate-400">Daily times use <code>PRODUCTIV_TIMEZONE</code>. Every run is written to the evidence log.</p></div></div>
 <div className="space-y-3">{loading?<div className="card p-10"><Loader2 className="w-5 h-5 animate-spin mx-auto text-brand-500"/></div>:rules.length===0?<div className="card p-10 text-center"><Activity className="w-8 h-8 mx-auto text-slate-200"/><p className="text-sm text-slate-500 mt-2">No automations configured.</p></div>:rules.map(r=><div className="card p-5" key={r.id}><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className={`w-2.5 h-2.5 rounded-full ${r.enabled?'bg-emerald-500':'bg-slate-300'}`}/><h3 className="font-bold text-slate-900">{r.name}</h3></div><p className="text-xs text-slate-500 mt-1">{r.trigger_type==='daily'?`Daily at ${String(r.trigger_config.hour).padStart(2,'0')}:${String(r.trigger_config.minute).padStart(2,'0')}`:`Every ${r.trigger_config.minutes} minute(s)`} → {r.action_type==='create_task'?'create + route duty':'send runtime message'}</p></div><button className="btn-secondary" disabled={busy===r.id} onClick={()=>toggle(r)}>{r.enabled?<><Pause className="w-4 h-4"/>Pause</>:<><Play className="w-4 h-4"/>Enable</>}</button></div><div className="mt-4 grid md:grid-cols-3 gap-3 text-xs"><div><p className="text-slate-400">Verified runs</p><p className="font-semibold text-slate-700 mt-0.5">{r.run_count}</p></div><div><p className="text-slate-400">Last run</p><p className="font-semibold text-slate-700 mt-0.5">{r.last_run_at?new Date(r.last_run_at).toLocaleString():'Never'}</p></div><div><p className="text-slate-400">Last error</p><p className={`font-semibold mt-0.5 ${r.last_error?'text-rose-600':'text-slate-700'}`}>{r.last_error||'None recorded'}</p></div></div></div>)}</div></div>
 </div></div></div>
}
