import { useCallback, useEffect, useState } from 'react';
import { TopBar } from '@/components/Sidebar';
import { orchestratorFetch, type Connector } from '@/lib/orchestrator';
import { CheckCircle2, KeyRound, Link2, Loader2, Plus, RefreshCw, Shield, XCircle } from 'lucide-react';

export function ConnectionsPage(){
  const [items,setItems]=useState<Connector[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(''); const [error,setError]=useState('');
  const [form,setForm]=useState({name:'',connector_type:'http',transport:'http',endpoint:'',secret_ref:''});
  const load=useCallback(async()=>{try{setError('');setItems(await orchestratorFetch<Connector[]>('/api/orchestration/connectors'));}catch(e){setError(e instanceof Error?e.message:'Unable to load connections')}finally{setLoading(false)}},[]); useEffect(()=>{load()},[load]);
  const add=async()=>{if(!form.name.trim())return;setBusy('add');try{await orchestratorFetch('/api/orchestration/connectors',{method:'POST',body:JSON.stringify({...form,endpoint:form.endpoint||null,secret_ref:form.secret_ref||null})});setForm({name:'',connector_type:'http',transport:'http',endpoint:'',secret_ref:''});await load();}catch(e){setError(e instanceof Error?e.message:'Create failed')}finally{setBusy('')}};
  const verify=async(id:string)=>{setBusy(id);try{await orchestratorFetch(`/api/orchestration/connectors/${id}/verify`,{method:'POST',body:'{}'});}catch(e){setError(e instanceof Error?e.message:'Verification failed')}finally{setBusy('');await load()}};
  return <div className="flex-1 flex flex-col overflow-hidden"><TopBar title="Connections" subtitle="Endpoints and secret references — credentials never enter the browser" actions={<button className="btn-secondary" onClick={load}><RefreshCw className="w-4 h-4"/>Refresh</button>}/><div className="flex-1 overflow-y-auto mesh-bg p-6"><div className="max-w-5xl mx-auto space-y-6">
    <div className="card p-5 border-brand-100 bg-gradient-to-br from-white to-brand-50/40"><div className="flex gap-3"><Shield className="w-5 h-5 text-brand-600 mt-0.5"/><div><h3 className="font-bold text-slate-900">Secret-reference model</h3><p className="text-sm text-slate-600 mt-1">Store only an environment-variable name such as <code>VIVIENNE_BASE44_TOKEN</code>. Productiv resolves it server-side for verification. Raw tokens are never stored in this UI or orchestration database.</p></div></div></div>
    {error&&<div className="card p-4 border-rose-200 bg-rose-50 text-rose-700 text-sm flex gap-2"><XCircle className="w-4 h-4"/>{error}</div>}
    <div className="grid lg:grid-cols-[360px_1fr] gap-5"><div className="card p-5 h-fit"><h3 className="font-bold text-slate-900 mb-4">Add connection</h3><div className="space-y-3"><input className="input" placeholder="Name (e.g. Vivienne API)" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select className="input" value={form.connector_type} onChange={e=>setForm({...form,connector_type:e.target.value})}><option value="http">HTTP service</option><option value="base44">Base44 Superagent</option><option value="hermes">Hermes runtime</option><option value="telegram">Telegram bot bridge</option><option value="mcp">MCP server</option></select><input className="input" type="url" placeholder="Health/API endpoint" value={form.endpoint} onChange={e=>setForm({...form,endpoint:e.target.value})}/><div className="relative"><KeyRound className="absolute left-3 top-2.5 w-4 h-4 text-slate-400"/><input className="input pl-9 font-mono" placeholder="SECRET_ENV_NAME (optional)" value={form.secret_ref} onChange={e=>setForm({...form,secret_ref:e.target.value.replace(/[^A-Za-z0-9_]/g,'').toUpperCase()})}/></div><button className="btn-primary w-full" disabled={busy==='add'||!form.name.trim()} onClick={add}>{busy==='add'?<Loader2 className="w-4 h-4 animate-spin"/>:<Plus className="w-4 h-4"/>}Add</button></div></div>
      <div className="space-y-3">{loading?<div className="card p-10 text-center"><Loader2 className="w-5 h-5 animate-spin mx-auto text-brand-500"/></div>:items.length===0?<div className="card p-10 text-center"><Link2 className="w-8 h-8 mx-auto text-slate-200"/><p className="text-sm text-slate-500 mt-2">No connections configured.</p></div>:items.map(c=><div className="card p-5" key={c.id}><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h3 className="font-bold text-slate-900">{c.name}</h3><span className={`badge ${c.verification_status==='verified'?'bg-emerald-50 text-emerald-700 border-emerald-200':c.verification_status==='failed'?'bg-rose-50 text-rose-700 border-rose-200':'bg-slate-50 text-slate-600 border-slate-200'}`}>{c.verification_status==='verified'?<CheckCircle2 className="w-3 h-3"/>:null}{c.verification_status}</span></div><p className="text-xs text-slate-500 mt-1">{c.connector_type} · {c.transport}</p></div><button className="btn-secondary" disabled={busy===c.id||!c.endpoint} onClick={()=>verify(c.id)}>{busy===c.id?<Loader2 className="w-4 h-4 animate-spin"/>:<RefreshCw className="w-4 h-4"/>}Verify</button></div><dl className="grid md:grid-cols-2 gap-3 mt-4 text-xs"><div><dt className="text-slate-400">Endpoint</dt><dd className="text-slate-700 font-mono break-all mt-0.5">{c.endpoint||'Not set'}</dd></div><div><dt className="text-slate-400">Secret reference</dt><dd className="text-slate-700 font-mono mt-0.5">{c.secret_ref||'None'}</dd></div><div><dt className="text-slate-400">Last verified</dt><dd className="text-slate-700 mt-0.5">{c.last_verified_at?new Date(c.last_verified_at).toLocaleString():'Never'}</dd></div><div><dt className="text-slate-400">Last error</dt><dd className="text-slate-700 mt-0.5">{c.last_error||'None recorded'}</dd></div></dl></div>)}</div></div>
  </div></div></div>
}
