import { useCallback, useEffect, useMemo, useState } from 'react';
import { TopBar } from '@/components/Sidebar';
import { orchestratorFetch, type RuntimeAgent, type OrchestrationTask } from '@/lib/orchestrator';
import { Activity, Bot, CheckCircle2, ClipboardCheck, Clock3, Copy, MessageSquare, Network, Play, Plus, RefreshCw, ShieldCheck, Terminal, XCircle, type LucideIcon } from 'lucide-react';

type Summary={agents:RuntimeAgent[];task_counts:{status:string;count:number}[];reports:{id:string;agent_name:string;report_type:string;report_date:string;summary:string;created_at:string}[];events:{id:string;actor:string;action:string;subject_type:string|null;subject_id:string|null;created_at:string;detail:unknown}[];server_time:string};
type BusMessage={id:string;correlation_id:string;from_name:string|null;to_name:string|null;type:string;body:string;created_at:string;read_at:string|null};
const since=(v:string|null)=>!v?'Never':new Intl.RelativeTimeFormat('en',{numeric:'auto'}).format(-Math.max(1,Math.round((Date.now()-Date.parse(v))/60000)),'minute');
const stateClass=(s:string)=>s==='online'?'bg-emerald-50 text-emerald-700 border-emerald-200':s==='stale'?'bg-amber-50 text-amber-700 border-amber-200':s==='registered'?'bg-sky-50 text-sky-700 border-sky-200':'bg-slate-50 text-slate-600 border-slate-200';

export function OrchestrationPage(){
  const [summary,setSummary]=useState<Summary|null>(null); const [tasks,setTasks]=useState<OrchestrationTask[]>([]); const [messages,setMessages]=useState<BusMessage[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [tab,setTab]=useState<'command'|'tasks'|'messages'|'reports'|'evidence'>('command');
  const [runtimeForm,setRuntimeForm]=useState({name:'',kind:'telegram_bot',capabilities:''});
  const [invite,setInvite]=useState<{agent:string;token:string;expires:string}|null>(null); const [taskForm,setTaskForm]=useState({title:'',description:'',capabilities:'',priority:'50'}); const [messageForm,setMessageForm]=useState({to:'',body:''});
  const load=useCallback(async()=>{try{setError('');const [s,t,m]=await Promise.all([orchestratorFetch<Summary>('/api/orchestration/summary'),orchestratorFetch<OrchestrationTask[]>('/api/orchestration/tasks'),orchestratorFetch<BusMessage[]>('/api/orchestration/messages')]);setSummary(s);setTasks(t);setMessages(m);}catch(e){setError(e instanceof Error?e.message:'Orchestrator unavailable')}},[]);
  useEffect(()=>{load();const id=setInterval(load,30000);return()=>clearInterval(id)},[load]);
  const counts=useMemo(()=>Object.fromEntries((summary?.task_counts||[]).map(x=>[x.status,Number(x.count)])),[summary]);
  const inviteAgent=async(a:RuntimeAgent)=>{setBusy(true);try{const r=await orchestratorFetch<{invite_token:string;expires_at:string}>(`/api/orchestration/agents/${a.id}/invite`,{method:'POST',body:JSON.stringify({ttl_minutes:60})});setInvite({agent:a.name,token:r.invite_token,expires:r.expires_at});}catch(e){setError(e instanceof Error?e.message:'Invite failed')}finally{setBusy(false)}};
  const createRuntime=async()=>{if(!runtimeForm.name.trim())return;setBusy(true);try{await orchestratorFetch('/api/orchestration/agents',{method:'POST',body:JSON.stringify({name:runtimeForm.name.trim(),kind:runtimeForm.kind,capabilities:runtimeForm.capabilities.split(',').map(x=>x.trim()).filter(Boolean)})});setRuntimeForm({name:'',kind:'telegram_bot',capabilities:''});await load();}catch(e){setError(e instanceof Error?e.message:'Runtime creation failed')}finally{setBusy(false)}};
  const createTask=async()=>{if(!taskForm.title.trim())return;setBusy(true);try{await orchestratorFetch('/api/orchestration/tasks',{method:'POST',body:JSON.stringify({title:taskForm.title.trim(),description:taskForm.description.trim(),required_capabilities:taskForm.capabilities.split(',').map(x=>x.trim()).filter(Boolean),priority:Number(taskForm.priority)||50})});setTaskForm({title:'',description:'',capabilities:'',priority:'50'});await load();}catch(e){setError(e instanceof Error?e.message:'Task creation failed')}finally{setBusy(false)}};
  const sendMessage=async()=>{if(!messageForm.to||!messageForm.body.trim())return;setBusy(true);try{await orchestratorFetch('/api/orchestration/messages',{method:'POST',body:JSON.stringify({to_agent_id:messageForm.to,body:messageForm.body.trim()})});setMessageForm({to:'',body:''});await load();}catch(e){setError(e instanceof Error?e.message:'Message failed')}finally{setBusy(false)}};
  const runScheduler=async()=>{setBusy(true);try{await orchestratorFetch('/api/orchestration/scheduler/run',{method:'POST',body:'{}'});await load();}catch(e){setError(e instanceof Error?e.message:'Scheduler failed')}finally{setBusy(false)}};
  return <div className="flex-1 flex flex-col overflow-hidden">
    <TopBar title="Orchestration" subtitle="One verified task bus for agents, harnesses and bots" actions={<div className="flex gap-2"><button className="btn-secondary" onClick={load}><RefreshCw className="w-4 h-4"/>Refresh</button><button className="btn-primary" disabled={busy} onClick={runScheduler}><Play className="w-4 h-4"/>Run router</button></div>}/>
    <div className="flex-1 overflow-y-auto mesh-bg p-6"><div className="max-w-7xl mx-auto space-y-5">
      {error&&<div className="card p-4 border-rose-200 bg-rose-50 text-rose-700 text-sm flex gap-2"><XCircle className="w-4 h-4 mt-0.5"/>{error}</div>}
      <div className="flex gap-1 p-1 bg-white border border-slate-200 rounded-xl w-fit">{([['command','Command Center'],['tasks','Task Queue'],['messages','Message Bus'],['reports','Daily Reports'],['evidence','Evidence Log']] as const).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 rounded-lg text-sm font-medium ${tab===id?'bg-brand-50 text-brand-700':'text-slate-500 hover:bg-slate-50'}`}>{label}</button>)}</div>
      {tab==='command'&&<>
        <div className="grid md:grid-cols-4 gap-4">
          <Metric icon={Network} label="Runtime slots" value={String(summary?.agents.length??0)} note={`${summary?.agents.filter(a=>a.state==='online').length??0} online now`}/>
          <Metric icon={Clock3} label="Queued" value={String(counts.queued||0)} note="Awaiting a verified match"/>
          <Metric icon={Activity} label="Active" value={String((counts.assigned||0)+(counts.claimed||0)+(counts.in_progress||0))} note="Assigned / claimed / working"/>
          <Metric icon={CheckCircle2} label="Completed" value={String(counts.completed||0)} note="Evidence required by API"/>
        </div>
        <div className="card p-4"><div className="grid lg:grid-cols-[1.2fr_1fr_1.5fr_auto] gap-2 items-end"><div><label className="text-[11px] font-semibold text-slate-500">Add real runtime</label><input className="input mt-1" placeholder="Bot or agent name" value={runtimeForm.name} onChange={e=>setRuntimeForm({...runtimeForm,name:e.target.value})}/></div><div><label className="text-[11px] font-semibold text-slate-500">Kind</label><select className="input mt-1" value={runtimeForm.kind} onChange={e=>setRuntimeForm({...runtimeForm,kind:e.target.value})}><option value="telegram_bot">Telegram bot</option><option value="hermes_vps">Hermes VPS</option><option value="hermes_managed">Hermes Managed</option><option value="base44_superagent">Base44 Superagent</option><option value="openclaw">OpenClaw</option><option value="harness">Other harness</option></select></div><div><label className="text-[11px] font-semibold text-slate-500">Capabilities</label><input className="input mt-1" placeholder="research, coding, support" value={runtimeForm.capabilities} onChange={e=>setRuntimeForm({...runtimeForm,capabilities:e.target.value})}/></div><button className="btn-primary" disabled={busy||!runtimeForm.name.trim()} onClick={createRuntime}><Plus className="w-4 h-4"/>Add slot</button></div></div>
        <div className="card overflow-hidden"><div className="px-5 py-4 border-b border-slate-100 flex items-center justify-between"><div><h3 className="font-bold text-slate-900">Runtime registry</h3><p className="text-xs text-slate-500">Status is derived only from registration and heartbeat timestamps.</p></div><ShieldCheck className="w-5 h-5 text-brand-600"/></div>
          <div className="divide-y divide-slate-100">{summary?.agents.map(a=><div key={a.id} className="p-4 grid lg:grid-cols-[1.5fr_1fr_1.4fr_auto] gap-4 items-center"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center"><Bot className="w-5 h-5 text-slate-600"/></div><div><p className="font-semibold text-slate-900">{a.name}</p><p className="text-xs text-slate-500">{a.kind.replaceAll('_',' ')}</p></div></div><div><span className={`badge ${stateClass(a.state)}`}>{a.state}</span><p className="text-[11px] text-slate-400 mt-1">Last seen: {since(a.last_seen_at)}</p></div><div className="flex flex-wrap gap-1">{a.capabilities.slice(0,4).map(c=><span key={c} className="badge bg-white text-slate-600 border-slate-200">{c}</span>)}</div><button className="btn-secondary" disabled={busy} onClick={()=>inviteAgent(a)}>{a.registered?'Rotate access':'Connect'}</button></div>)}</div>
        </div>
        {invite&&<div className="card p-5 border-brand-200"><div className="flex items-start justify-between gap-4"><div><h3 className="font-bold text-slate-900">One-time connection invite — {invite.agent}</h3><p className="text-xs text-slate-500 mt-1">Expires {new Date(invite.expires).toLocaleString()}. Productiv stores only a hash; this value is shown once.</p></div><button className="btn-secondary" onClick={()=>navigator.clipboard.writeText(invite.token)}><Copy className="w-4 h-4"/>Copy</button></div><code className="block mt-3 p-3 rounded-lg bg-slate-950 text-slate-100 text-xs break-all">{invite.token}</code><p className="text-xs text-slate-500 mt-3">Register at <code>POST /api/agent/register</code>. The returned runtime token can also authenticate the <code>/mcp</code> endpoint.</p></div>}
      </>}
      {tab==='tasks'&&<div className="grid lg:grid-cols-[360px_1fr] gap-5"><div className="card p-5 h-fit"><h3 className="font-bold text-slate-900 mb-4">New duty</h3><div className="space-y-3"><input className="input" placeholder="Task title" value={taskForm.title} onChange={e=>setTaskForm({...taskForm,title:e.target.value})}/><textarea className="input min-h-24" placeholder="Acceptance criteria / instructions" value={taskForm.description} onChange={e=>setTaskForm({...taskForm,description:e.target.value})}/><input className="input" placeholder="Capabilities, comma-separated" value={taskForm.capabilities} onChange={e=>setTaskForm({...taskForm,capabilities:e.target.value})}/><input className="input" type="number" min="1" max="100" value={taskForm.priority} onChange={e=>setTaskForm({...taskForm,priority:e.target.value})}/><button className="btn-primary w-full" disabled={busy||!taskForm.title.trim()} onClick={createTask}><Plus className="w-4 h-4"/>Route duty</button><p className="text-[11px] text-slate-400">Routing is deterministic: capability match, then least active workload. No generated scores.</p></div></div><div className="space-y-3">{tasks.length===0?<Empty text="No duties have been created."/>:tasks.map(t=><div key={t.id} className="card p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{t.title}</p><p className="text-sm text-slate-500 mt-1">{t.description||'No description'}</p></div><span className="badge bg-slate-50 text-slate-600 border-slate-200">{t.status}</span></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500"><span>Assignee: <b className="text-slate-700">{t.assignee_name||'Unassigned'}</b></span><span>Priority: {t.priority}</span><span>Correlation: <code>{t.correlation_id.slice(0,8)}</code></span></div>{t.routing_reason&&<p className="text-[11px] text-slate-400 mt-2">Route: {t.routing_reason}</p>}{t.evidence?.length>0&&<div className="mt-3 p-3 bg-emerald-50 rounded-lg text-xs text-emerald-800"><b>Evidence:</b> {t.evidence.join(' · ')}</div>}</div>)}</div></div>}
      {tab==='messages'&&<div className="grid lg:grid-cols-[360px_1fr] gap-5"><div className="card p-5 h-fit"><h3 className="font-bold text-slate-900 mb-4">Send to runtime</h3><select className="input mb-3" value={messageForm.to} onChange={e=>setMessageForm({...messageForm,to:e.target.value})}><option value="">Select runtime</option>{summary?.agents.map(a=><option key={a.id} value={a.id}>{a.name} — {a.state}</option>)}</select><textarea className="input min-h-28" placeholder="Message or handoff" value={messageForm.body} onChange={e=>setMessageForm({...messageForm,body:e.target.value})}/><button className="btn-primary w-full mt-3" onClick={sendMessage} disabled={busy||!messageForm.to||!messageForm.body.trim()}><MessageSquare className="w-4 h-4"/>Send</button></div><div className="space-y-2">{messages.length===0?<Empty text="No runtime messages yet."/>:messages.map(m=><div key={m.id} className="card p-4"><div className="flex justify-between gap-3"><p className="text-sm font-semibold text-slate-800">{m.from_name||'Productiv'} → {m.to_name||'Unaddressed'}</p><span className="text-[11px] text-slate-400">{new Date(m.created_at).toLocaleString()}</span></div><p className="text-sm text-slate-600 mt-2 whitespace-pre-wrap">{m.body}</p><p className="text-[10px] text-slate-400 mt-2">{m.type} · {m.correlation_id}</p></div>)}</div></div>}
      {tab==='reports'&&<div className="space-y-3">{!summary?.reports.length?<Empty text="No daily check-ins or check-outs have been submitted."/>:summary.reports.map(r=><div key={r.id} className="card p-4 flex gap-3"><ClipboardCheck className="w-5 h-5 text-brand-600 mt-0.5"/><div><p className="font-semibold text-slate-900">{r.agent_name} · {r.report_type} · {r.report_date}</p><p className="text-sm text-slate-600 mt-1 whitespace-pre-wrap">{r.summary}</p><p className="text-[11px] text-slate-400 mt-1">Received {new Date(r.created_at).toLocaleString()}</p></div></div>)}</div>}
      {tab==='evidence'&&<div className="space-y-2">{!summary?.events.length?<Empty text="No orchestration events recorded."/>:summary.events.map(e=><div key={e.id} className="card px-4 py-3 grid md:grid-cols-[180px_1fr_220px] gap-3 text-sm"><code className="text-xs text-slate-500">{new Date(e.created_at).toLocaleString()}</code><div><b className="text-slate-800">{e.action}</b><span className="text-slate-500"> · {e.actor}</span></div><code className="text-xs text-slate-400 truncate">{e.subject_type||''}:{e.subject_id||''}</code></div>)}</div>}
    </div></div>
  </div>
}
function Metric({icon:Icon,label,value,note}:{icon:LucideIcon;label:string;value:string;note:string}){return <div className="card p-4"><div className="flex items-center gap-2 text-slate-500 text-xs font-medium"><Icon className="w-4 h-4"/>{label}</div><p className="text-3xl font-black text-slate-900 mt-2">{value}</p><p className="text-[11px] text-slate-400 mt-1">{note}</p></div>}
function Empty({text}:{text:string}){return <div className="card p-10 text-center text-slate-400"><Terminal className="w-8 h-8 mx-auto mb-2 text-slate-200"/><p className="text-sm">{text}</p></div>}
